services:
  app:
    build: ./app
    container_name: sheet-book-app
    restart: unless-stopped
    networks:
      - sheet-book
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
  
  web:
    build: ./web
    container_name: sheet-book-cli
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - sheet-book
    ports:
      - 8081:8081
    volumes:
      - type: bind
        source: ./web
        target: /app
      - /app/node_modules
    expose:
      - 8081

networks:
  sheet-book:
    name: sheet-book
    driver: bridge